---
 - name: Download the memory plugin
   get_url:
    url: https://raw.githubusercontent.com/justintime/nagios-plugins/master/check_mem/check_mem.pl
    dest: /usr/lib/nagios/plugins/check_mem.pl
    mode: 0755
   become: true
 - name: Install the memory check command
   copy:
    src: files/memory.conf
    dest: /usr/share/icinga2/include/plugins-contrib.d/memory.conf
    owner: root
    group: root
    mode: 0644
   become: true
 - name: Download the fd plugin
   get_url:
    url: https://exchange.nagios.org/components/com_mtree/attachment.php?link_id=2767&cf_id=24
    dest: /usr/lib/nagios/plugins/check_fd
    mode: 0755
   become: true
 - name: Install the fd check command
   copy:
    src: files/fd.conf
    dest: /usr/share/icinga2/include/plugins-contrib.d/fd.conf
    owner: root
    group: root
    mode: 0644
   become: true
 - name: "Install mpstat"
   apt: 
    name: sysstat
    state: present
 - name: Install the mpstat plugin
   copy:
    src: files/check_mpstat.sh
    dest: /usr/lib/nagios/plugins/check_mpstat.sh
    owner: root
    group: root
    mode: 0755
 - name: Install the mpstat check command
   copy:
    src: files/mpstat.conf
    dest: /usr/share/icinga2/include/plugins-contrib.d/mpstat.conf
    owner: root
    group: root
    mode: 0644
   become: true
 - name: Install the statsjobrun plugin
   copy:
    src: files/check_statsjobrun.sh
    dest: /usr/lib/nagios/plugins/check_statsjobrun.sh
    owner: root
    group: root
    mode: 0755
 - name: Install the statsjobrun check command
   copy:
    src: files/statsjobrun.conf
    dest: /usr/share/icinga2/include/plugins-contrib.d/statsjobrun.conf
    owner: root
    group: root
    mode: 0644
   become: true
   
 - name: Reload Icinga On Client
   service:
        name: icinga2
        state: reloaded
   become: true
   ignore_errors: true
